### ISSUE TITLE
Slow font loading (20 secs)

### ISSUE THREAD

**Issue by toyboot4e** [mooman219/fontdue#102]
It takes 20 seconds to load [M PLUS 1p][f] font (regular) with `fontdue::Font::load_bytes` on my mac. I tried it in both debug and release build, but the result did not change much. Can I make it faster?

[f]: https://fonts.google.com/specimen/M+PLUS+1p

Examples worked very fast 👍

**Comment by mooman219** [comment]
`load_bytes` isn't a function. Did you mean `from_bytes`?

I downloaded `MPLUS1p-Regular.ttf` and ran it and it loaded in a few milliseconds on release. Do you have any additional information or profile because I cannot reproduce this locally.

**Comment by toyboot4e** [comment]
> Did you mean `from_bytes`?

It's `from_bytes` /

> it loaded in a few milliseconds on release via the simple example

It worked lightning fast! I think I just failed to specify `--release`.

I'm sorry. Thank you for checking it out.

**Comment by toyboot4e** [comment]
I added the following to `/my/repository/.cargo/config.toml`:

```toml
[profile.dev.package."ttf-parser"]
opt-level = 3
```
