### ISSUE TITLE
GPU Rendering

### ISSUE THREAD

**Issue by deeprobin** [mooman219/fontdue#105]
I have a small suggestion (with probably big implementation). It's about a dependent being able to enable GPU rendering by means of a cargo feature.

Of course it would make sense to determine a certain value, which says from which text complexity the rendering on the GPU is worthwhile.
Simply running everything on the GPU would not be a good idea in my opinion, since there is a GPU overhead. 

You could take a look at [wgpu](https://github.com/gfx-rs/wgpu/tree/v0.12).

**Comment by mooman219** [comment]
Sorry, I have no intention of any GPU integration. You should checkout the glorious [pathfinder](https://github.com/servo/pathfinder) if you're looking for a gpu rasterized font and graphics library.
