### ISSUE TITLE
Occurrences of unsafe can be replaced with safe versions

### ISSUE THREAD

**Issue by e00E** [mooman219/fontdue#107]
I checked a couple of uses of unsafe in this crate and found that they can be replaced with safe versions that generate the same assembly with optimizations. There are probably more instances of this.

- https://github.com/mooman219/fontdue/blob/c36144652fee3c33f6b763d3171785c5c95816fe/src/platform/float/mod.rs#L35-L39
https://godbolt.org/z/z4x3hEPa3
- https://github.com/mooman219/fontdue/blob/c36144652fee3c33f6b763d3171785c5c95816fe/src/font.rs#L611-L613
https://godbolt.org/z/hbz5sjhPa

On that note it is worrying that many uses of unsafe are not documented. I feel their impact should be benchmarked versus safe versions and their correctness should be explained. For example the second link above, with the transmute, seems like undefined behavior to me because I am not sure that Rust guarantees that the layout matches this way.

**Comment by mooman219** [comment]
Oh both of these are fine. 

For the first, yeahhhh I'll swap that to to/from bits and drop the unsafe.

For the second, specifically rust guarantees `NonZeroU16`'s layout is the same as a `u16`, it's in the official docs. I'll add a comment.

**Comment by mooman219** [comment]
> I am not sure that NonZeroU16 is guaranteed to have the same layout as u16. I couldn't find this statement in the standard library's documentation.

https://doc.rust-lang.org/beta/std/num/struct.NonZeroU16.html

It is guaranteed that None has the same bit pattern as 0u16 for NonZeroU16.
It is guaranteed that NonZeroU16 has the same layout as u16.
All nonzero_integers follow this behavior and this is the intended use case.
If this behavior changes in the future it will require a new rust edition.

**Comment by e00E** [comment]
The second link explicitly states

> It is further guaranteed that, for the cases above, one can [mem::transmute](https://doc.rust-lang.org/std/mem/fn.transmute.html) from all valid values of T to Option<T> and from Some::<T>(_) to T (**but transmuting None::<T> to T is undefined behaviour**).

**Comment by mooman219** [comment]
There was a proposal for f32s as well which that would apply to, but otherwise it can't settle on any other value for the existing NonZeroU8/16/32/etc.

**Comment by mooman219** [comment]
I'm fine with the assumption. Logically it has to be 0 otherwise it invalidates their other guarantees, at which point I have other issues. If we assume the current guarantees are silently removed within the same rust edition, and consider the value random over the entire space, it also doesn't matter since this is consumed by a bounds check, which CI would catch.

**Comment by e00E** [comment]
I just realized I did not read

> but transmuting None::<T> to T is undefined behaviour

carefully enough. We are transmuting `None::<NonZeroU16>` to `u16` not to `NonZeroU16` so I no longer believe that the documentation clearly states that this is UB.

**Comment by e00E** [comment]
My conclusion after asking around:
This not UB based on current compiler internals but also not guaranteed not UB based on current documentation. It is something that is intended you can do with these types and likely to be guaranteed not UB at some point in the future.

I no longer believe there is a serious defect. I still believe it would be better to use the same assembly producing safe version but either choice is no big deal.

**Comment by mooman219** [comment]
ok
