### ISSUE TITLE
rasterization appears slightly tessellated

### ISSUE THREAD

**Issue by wtholliday** [mooman219/fontdue#109]
I noticed when scrutinizing glyphs rendered by fontdue that they seem a bit tessellated, as if the bezier curves aren't being evaluated at high enough resolution. For example, here's a glyph rendered by fontdue:

<img width="78" alt="image" src="https://user-images.githubusercontent.com/841144/162248463-b016edee-dbc8-475c-94db-146ed54a355b.png">

Notice the tessellation of the interior curves.

versus the same glyph rendered in Apple's Font Book:

<img width="83" alt="image" src="https://user-images.githubusercontent.com/841144/162248697-4686a57c-64d4-4a4c-8ca2-a1e14d906b34.png">

I can provide more detailed information if necessary. The font is "Anodina Regular"

**Comment by mooman219** [comment]
See: https://docs.rs/fontdue/latest/fontdue/struct.FontSettings.html scale
