### ISSUE TITLE
Some pixel font rasterize incorrect

### ISSUE THREAD

**Issue by TakWolf** [mooman219/fontdue#11]
https://github.com/SolidZORO/zpix-pixel-font/tree/master/dist

Zpix is a pixel font. Standard size is 12px. Is rasterize ok on multiple of 12px.
But in some size the rasterize is incorrect.

For example:

size = 12px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77497082-66a5be80-6e87-11ea-8548-95fb2068a6b6.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77497288-edf33200-6e87-11ea-804c-1de7e8e7162d.png)

size = 32px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77497016-437b0f00-6e87-11ea-9ec1-b8b2f8df0355.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77497325-04998900-6e88-11ea-97c6-d136760506ba.png)

size = 48px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77497993-98b82000-6e89-11ea-9a46-07127ea28f3e.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77498034-aa012c80-6e89-11ea-9ce0-32a43883a240.png)

size = 64px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77498074-bf765680-6e89-11ea-871b-c333c4da6472.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77498087-cb621880-6e89-11ea-941f-2d5b732718f2.png)

There some lines in bottom.

=================================

https://purestudio.itch.io/ipix

IPix is another pixel font. Recommand size is 12px, but actually is 16px.

size = 12px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77497560-95706480-6e88-11ea-9155-289d6491c83e.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77497589-ab7e2500-6e88-11ea-8d2c-ecc1907f1ab2.png)

size = 16px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77497666-d7010f80-6e88-11ea-9601-d2bdf3a7607b.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77497693-e4b69500-6e88-11ea-81c0-b6ac59721a24.png)

size = 48px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77497816-33fcc580-6e89-11ea-881f-2be3cc8ac56f.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77497844-4414a500-6e89-11ea-9fee-ce12b943d213.png)

size = 64px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77497891-5ee71980-6e89-11ea-9aef-898c40c5f7ad.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77497915-6b6b7200-6e89-11ea-9278-286faf77606c.png)

=============================
rusttype can rasterize correct, but lost hard edge.

Zpix.ttf

size = 12px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77498815-80490500-6e8b-11ea-85ce-93db8ff622c1.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77498837-8fc84e00-6e8b-11ea-9216-dd6c6565e9ca.png)

size = 48px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77498674-2cd6b700-6e8b-11ea-9e08-81feabf31c78.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77498698-40821d80-6e8b-11ea-840b-62a0b1d9c8e2.png)

size = 64px

`a`:
![image](https://user-images.githubusercontent.com/6064962/77498722-52fc5700-6e8b-11ea-8ef1-c3b6090ab164.png)
`你`:
![image](https://user-images.githubusercontent.com/6064962/77498749-60194600-6e8b-11ea-86af-720903bc48f4.png)

**Comment by mooman219** [comment]
oh god zpix has 22,000 glyphs. I'll look into those issues

**Comment by mooman219** [comment]
As for the lines, it is unfortunate. The issue is rounding errors with single precision floats and I'm looking into ways to fix it. I have a `TODO` for this in code right now [here](https://github.com/mooman219/fontdue/blob/master/src/raster.rs#L71).

I can render it correctly, but it introduces errors at higher sizes right now due to precision loss.
![image](https://user-images.githubusercontent.com/865769/77502816-30315a80-6e19-11ea-8df8-6789cecf1c70.png)

**Comment by mooman219** [comment]
I pushed a change to resolve this here https://github.com/mooman219/fontdue/commit/c4bd8a0496a74b1ccc3d6322dfc533f1ecd11a72. 

![image](https://user-images.githubusercontent.com/865769/77510484-282ee600-6e2c-11ea-9b6b-33febaf7bce6.png)

**Comment by TakWolf** [comment]
```
    /// Retrieves the layout metrics and rasterized bitmap for the given character. If the caracter
    /// isn't present in the font, then the layout and bitmap for the font's default character is
    /// returned instead.
    pub fn rasterize(&self, character: char, px: f32) -> (Metrics, Vec<u8>) {
        self.rasterize_indexed(self.lookup_glyph_index(character), px)
    }
```
So this function's param `px` is pixel, but not point?
The right way to use fontdue rasterize is use pixel?

The Zpix font recommend size unit is actually pixel.
![image](https://user-images.githubusercontent.com/6064962/77511560-49371b80-6eac-11ea-9aa0-a8b996578b1d.png)
Fontdue rasterized Zpix in 12px is great! It retained the hard border so make the pixel style. 

Opposite rusttype can not rasterized Zpix in 12px as well (looks like linear filter?). That's why I gave up on it. I have making the pixel style game, so there is a way to  make text as pixel style is very important.
