### ISSUE TITLE
Super slow font loading

### ISSUE THREAD

**Issue by Yuri6037** [mooman219/fontdue#111]
When trying to load the system font `NotoSansCJK-Regular.ttc`, this library requires a nearly 5 to 10 minutes to load the file using `from_bytes`...

EDIT: With a bit of testing, the problem replicates with any font file that is greater than 1MB (unfortunately all Chinese compatible fonts I've seen are greater than 1MB in size).

**Comment by toyboot4e** [comment]
`ttf-parser` loads your fonts. You can try adding the following to `/your/repository/.cargo/config.toml`:

```toml
[profile.dev.package."ttf-parser"]
opt-level = 3
```

**Comment by Yuri6037** [comment]
I forgot to mention that the problem is the same even in release

**Comment by mooman219** [comment]
Can you provide the font?

Also have you tried the `parallel` feature if you're on not-web?

**Comment by Yuri6037** [comment]
> Seems fine for me. Benchmark:
> 
> ```
> fn fontdue() {
>     let settings = FontSettings {
>         scale: SIZE,
>         ..FontSettings::default()
>     };
>     let font = Font::from_bytes(font, settings).unwrap();
> }
> 
> load/fontdue NotoSansCJK-Regular time:   [342.99 ms 345.99 ms 349.19 ms]
> ```
> 
> Also have you tried the `parallel` feature for non-web environments (parallelization is a bit experimental on web still), it improves load times by quite a bit:
> 
> ```
> fontdue = { version = "0.7.2", features = ["parallel"] }
> 
> load/fontdue NotoSansCJK-Regular time:   [112.75 ms 115.23 ms 117.80 ms]
> ```

I will try again, but this time loading from disk directly instead of going through `include_bytes!`.

**Comment by Yuri6037** [comment]
Oh wow I figured it so first things first, `include_bytes!` does indeed grant the release build to be 0.909s instead of 5-10 minutes so I don't know exactly what `include_bytes!` does behind the scenes but in debug it's atrociously slow...

Now I've noticed something else: in my `Cargo.toml` I was using an older version of the library `0.6.2` instead of `0.7.2`. Once I've changed to `0.7.2` like you've shown, the library became lightning fast:

- Without `parallel`:
```
real    0m4.062s
user    0m3.993s
sys     0m0.069s
```

- With `parallel`:
```
real    0m1.442s
user    0m6.714s
sys     0m0.185s
```

**These numbers are for debug builds of course.**

**Comment by mooman219** [comment]
Sounds good, I'll close this as resolved.
