### ISSUE TITLE
Add other licensing options

### ISSUE THREAD

**Issue by lunabunn** [mooman219/fontdue#112]
Currently `fontdue` is licensed solely under `MIT`. In addition to not being as compatible as it could be with the rest of the ecosystem, most of which uses the `MIT OR Apache-2.0` dual license, `MIT` is also problematic in that in lacks a patent protection clause and an explicit contribution clause. In fact, [Rust itself is only keeping around `MIT` as a licensing option (instead of using just `Apache-2.0`) for GPLv2 compat](https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952/4).

If this project were to be dual-licensed under `Apache-2.0` and `MIT`, contributors would be providing the `Apache-2.0` patent grant, even though the project will still remain usable with the `MIT` license. It will also be more compatible with the rest of the ecosystem. I think this is the ideal option, especially for a crate such as `fontdue` that is more likely to end up in someone's dependency tree as an n-layers-deep indirect dependency than a direct one (having to deal with weird different licensing of some dependency of a dependency of a dependency is obviously not fun).

I would personally say that while we are at it we may as well also add the `Zlib` license to make it a `MIT or Apache-2.0 or Zlib` triple license, which would provide both the extra protection of `Apache-2.0` *and* the extra permissiveness of `Zlib`. However, I do remember #7 being closed as `wontfix`, so if that had anything to do with you not liking the license, just the dual license above would still be better than what we have now. You closed that issue saying you cannot relicense due to legal reasons; however, that was 2 years ago. Does that still apply/does it also apply to `Apache-2.0`?

Obviously, both `Apache-2.0` and `Zlib` are OSI-certified and relatively popular in the Rust community.

**Comment by mooman219** [comment]
#7 was closed because technically my employer owns this project and `zlib` wasn't an approved license at that time. I opened a ticket to add zlib which was resolved like a year later by the looks of it, so I should be able to use `zlib` now. Honestly though I'm not sure what I need to do to swap licenses since there's been a number of contributors and I haven't looked into it.

**Comment by mooman219** [comment]
Sounds good to me. I approve the license change to `MIT OR Apache-2.0 OR Zlib`.

I don't have the time right now to shepard the license change, so if you want to own the PR then I'll support it.

**Comment by grovesNL** [comment]
This is done now

**Comment by lunabunn** [comment]
Indeed, thanks! 🎉
