### ISSUE TITLE
Incorrect Colors in Web Demo

### ISSUE THREAD

**Issue by overdrivenpotato** [mooman219/fontdue#114]
The web demo [incorrectly interprets](https://github.com/mooman219/fontdue/blob/gh-pages/www/index.js#L54-L56) the renderer output as being in the sRGB colorspace. `ImageData` [expects sRGB colors by default](https://chromestatus.com/feature/5807007661555712), not linear. From the fontdue docs, [`fn rasterize`](https://docs.rs/fontdue/latest/fontdue/struct.Font.html#method.rasterize) returns a coverage `Vec<u8>` where coverage is a linear scale.

**Comment by mooman219** [comment]
@weswigham If you want to handle this
