### ISSUE TITLE
Can you add an example of how to create a simple letter and save as a font?

### ISSUE THREAD

**Issue by alexhallam** [mooman219/fontdue#134]
Say I want to make a "pixel" style font from scratch. For example the letter "p" would be represented as

```
    [
        [0, 1, 1, 0, 0],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 1, 0],
        [1, 1, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
    ]
```
<img width="245" alt="Screenshot 2023-02-10 at 5 49 39 PM" src="https://user-images.githubusercontent.com/9298693/218215759-b17bb024-38da-41e8-9e3f-e8fcbe1804af.png">

How can I create this letter and save as a `ttf` or `otf` using Rust and this library?

**Comment by mooman219** [comment]
You cannot use Fontdue to modify or create a new font, sorry! There's no intention of doing so either.
