### ISSUE TITLE
No ability to query font for its name

### ISSUE THREAD

**Issue by junglie85** [mooman219/fontdue#150]
I wanted to be able to get a font's name but the member isn't exposed publicly. I see there is already a PR adding this. https://github.com/mooman219/fontdue/pull/141. I would find this useful and am curious if there's anything preventing you from accepting this PR?

**Comment by Hugo4IT** [comment]
Same here, I need the font name as well. For now I guess I'll just use ttf_parser and accept the double parsing but it would be nice if #141 could be accepted if you have the time.

**Comment by mooman219** [comment]
Yeah sounds good, merged

**Comment by mooman219** [comment]
`0.9.2` published
