### ISSUE TITLE
segoe ui font displays linefeed character while calibri does not

### ISSUE THREAD

**Issue by ericlangedijk** [mooman219/fontdue#156]
Drawing text with Layout I noticed that the linebreak is displayed in Segoe UI and not with (for example) Calibri.
I can skip the display using CharacterInfo::is_control().
But I was wondering what is going on deep down and if there is a setting for this.

segoeui:
![image](https://github.com/user-attachments/assets/cdac7570-a293-4166-bc26-e8e7747ea959)

calibri:
![image](https://github.com/user-attachments/assets/873cd7da-bf89-4df6-aba3-57912dd7c032)

**Comment by mooman219** [comment]
What probably is happening is the font is providing a glyph for the control character and it just happens to be that box. Not all fonts provide one. Some people want control characters rendered, replaced, or skipped entirely, so fontdue provides `CharacterInfo::is_control`, as you saw, to let you decide and filter as needed. The intended use here is to skip control characters in your case.
