### ISSUE TITLE
bump hashbrown version

### ISSUE THREAD

**Issue by joseluis** [mooman219/fontdue#157]
Updating `hashbrown` to `0.15` changes its default hasher to `foldhash` instead of `ahash`, slightly improving performance and more importantly removing a few transitive dependencies (`cfg-if`, `once_cell`, `zerocopy`).

**Comment by mooman219** [comment]
@joseluis 

Sorry for the delay, I had major surgery and have been a out for a little. I'll get a new minor version out

**Comment by joseluis** [comment]
thank you, no hurries. I wish you have a good recovery.

**Comment by mooman219** [comment]
Done, thanks again!
