### ISSUE TITLE
[Hang] while parsing font

### ISSUE THREAD

**Issue by robmcl4** [mooman219/fontdue#16]
My fuzzer found a hang when attempting to parse the attached font using `Font::from_bytes(...)`

[hang.zip](https://github.com/mooman219/fontdue/files/4518344/hang.zip)

**Comment by mooman219** [comment]
Low priority to fix. Brainstorming, I assume I can set limits on various loops in say the cmap table, but I'll have to review what limits true type defines so I can hold the font file accountable.

**Comment by mooman219** [comment]
Fixed
