### ISSUE TITLE
[Segfault] in Raster::draw

### ISSUE THREAD

**Issue by robmcl4** [mooman219/fontdue#19]
My fuzzer found a segfault in Raster::draw while calling `font.render('g', 60.0)` for the included font file.
[segfault2.zip](https://github.com/mooman219/fontdue/files/4536537/segfault2.zip)

**Comment by mooman219** [comment]
Fixed, will upload the change. I love getting these absolute degenerate, nearly random data, font files. This new one you attached did some disgusting, very not in spec work on the geometry.
