### ISSUE TITLE
Visual quality regressions

### ISSUE THREAD

**Issue by MarimeGui** [mooman219/fontdue#23]
Hello again !

After upgrading my console from version 0.0.4 to 0.1.0 of fontdue, visual quality of the rendered characters significantly degraded.

Here is what it looked like before:
![Old](https://user-images.githubusercontent.com/3298928/85705385-72e92400-b6e1-11ea-8490-4d256b858113.png)

This is what it looks like now:
![New](https://user-images.githubusercontent.com/3298928/85705381-71b7f700-b6e1-11ea-9a8c-b72bc939d6e2.png)

(I am using font size 15.0 btw)

Certain characters look different, just slightly "denser" or "thinner" in certain areas. This is especially visible on 'o', 'a', 'g' and 'c' characters (mostly the ones that curve apparently).

It traced it back to [this](https://github.com/mooman219/fontdue/commit/3dad1c53c385aaf58962849755aa8b015157700a) commit, fixing the std problem where std ops were used by implementing a custom atan2 fn.

I tried replacing it by copy-pasting the one found in libm, and it fixed this issue, restoring back the look before this commit.

I tried looking for what's wrong in the new code, but I'm not smart enough sadly.

Do you think a fix is possible ?

Thanks again,
Marime Gui

**Comment by mooman219** [comment]
A test font I used showed no diff with the new atan2, but my test font is kinda bad. I'll swap to libm's correct atan2 since this doesn't impact performance, all these slower math bits are part of the precomputation on font creation.

**Comment by mooman219** [comment]
Can you give it a try with Sun's atan function? https://github.com/mooman219/fontdue/commit/f0054b67a709d953ab19107dbdb20616e62a908c

**Comment by MarimeGui** [comment]
Yup, that seems to have done the trick !
The rendered characters look exactly like before !
Thanks for the swift modification, I'll close this now.

**Comment by mooman219** [comment]
Awesome, I'll publish 0.1.1 today eventually
