### ISSUE TITLE
The letter "u" does not align correctly.

### ISSUE THREAD

**Issue by john01dav** [mooman219/fontdue#28]
Title pretty much says it all. The code that I'm using for layout is basically [this](https://github.com/mooman219/fontdue/issues/22#issuecomment-660563529), except the ymax variable is floored as soon as it's read to fix the issue that I was having when I posted that code. I'm not sure how much you'll care about this bug, given that proper layout is coming soon (I eagerly await this), but I figured that I should make you aware either way.

![image](https://user-images.githubusercontent.com/3982497/88470209-5ba77d00-cebf-11ea-8212-0b6aeba0259d.png)

**Comment by mooman219** [comment]
I don't really have time to review other code right now (a bit sick rn). I pushed the WIP layout code. Not everything is implemented, like vertical alignment. There's an example for how to use it here: https://github.com/mooman219/fontdue/blob/master/examples/layout.rs

**Comment by john01dav** [comment]
I'm working on integrating it into my code, but there's a problem. I have my fonts setup via the lazy_static crate, so I have them as `&'static Font`, and it looks like this is in compatible with the format requiring `&[Font]` (as opposed to, e.g. `&[&Font]`). Is this something that can get changed to allow it to be compatible with `&'static Font`? This is quite a reasonable way (until this issue) to keep all of my fonts cleanly initialized without causing them to be re-loaded each time some text is rendered.

**Comment by john01dav** [comment]
I found a workaround:
```rs
let font_array = unsafe{
    std::slice::from_raw_parts(font as *const Font, 1)
};
```
Obviously, however, this isn't ideal due to unsafe code.

**Comment by john01dav** [comment]
Using that workaround, the new layout engine seems to work very well. Thank you for the excellent library! :)

**Comment by mooman219** [comment]
It doesn't matter to me if it's &[font] or &[&font]. I'll look into adding support for &[&font]. I opted for the current one because that's what a vec would be.

**Comment by john01dav** [comment]
@mooman219 thanks for making that change :). I'd like to make you aware of [this](https://github.com/mooman219/fontdue/issues/1#issuecomment-668502202) before you push the new API to crates.io, in case you haven't seen it yet. Thanks again for the great library :)

**Comment by mooman219** [comment]
I pushed the change last night, tell me how it goes.

**Comment by john01dav** [comment]
I'm not sure what you're saying. I don't see a new push to crates.io, and I don't see anything about the alignment data for whitespace characters feature request in your recent commits (maybe I'm missing it?).
