### ISSUE TITLE
Some glyphs are missing coverage data for certain fonts

### ISSUE THREAD

**Issue by hasenbanck** [mooman219/fontdue#38]
While porting the font renderer for egui to fontdue, I happen to notice that some glyphs are missing the coverage data for a font that egui uses:
https://github.com/emilk/egui/blob/master/egui/fonts/Comfortaa-Regular.ttf

For example the glyph for the character 'b' only has a vector with coverage of "0.0"s, but on the other side, the metrics look fine.

Rusttype doesn't seem to have this problem.

**Comment by mooman219** [comment]
The font defines half of it's glyphs in TrueType, and the other half in OpenType. Some font viewers will have this issue as well because this is fairly _wrong_ all things considered. I'll see what I can do to support it

**Comment by mooman219** [comment]
Upon closer inspection, the letter 'b' is actually not to spec for the font. It's a transform of the letter 'd' which leaves the points incorrectly defined. I'll see what I can do to resolve that, but it's definitely going against the spec for the table the letter is defined in.

**Comment by mooman219** [comment]
Fixed
