### ISSUE TITLE
Possible word wrapping error when allowing wrap_hard_breaks

### ISSUE THREAD

**Issue by hasenbanck** [mooman219/fontdue#39]
Hi.

Given the following string:
https://github.com/emilk/egui/blob/a35fe7da126f82dcdf3738a250e150a5ff5d30bb/egui/src/demos/mod.rs#L19

I get the following output (please ignore the miss aligned glyphs for now):
<img width="495" alt="render" src="https://user-images.githubusercontent.com/12084860/96089339-fa43e880-0ec6-11eb-8126-494c88bcf519.png">

I used the following layout settings:
```rust
        let settings = LayoutSettings {
            max_width: max_width_in_points,
            wrap_hard_breaks: true,
            ..Default::default()
        };
```

Given these settings I would assume that line breaks are honoured and I get an empty line between the paragraphs. It also seems that after the line break, the wrapping isn't working anymore.

Is this the expected behaviour?

**Comment by mooman219** [comment]
That's incorrect and should be fixed.

**Comment by mooman219** [comment]
Should be fixed with the rewrite. Feel free to reopen this if it still shows up in 0.4 (not yet published, but on HEAD)
