### ISSUE TITLE
Line breaks when max_width is None

### ISSUE THREAD

**Issue by bschwind** [mooman219/fontdue#42]
Hi,

I'm not sure what the intended behavior is here, but when `max_width` is set to `None` in `LayoutSettings`, hard line breaks have no effect. Relevant code:

https://github.com/mooman219/fontdue/blob/3e2f51fe70fd7ab21ff70652ff8c2798f6e9fc65/src/layout.rs#L200

If this is intentional then that's totally fine, I'll specify a relevant maximum width.

Thanks for the great library!

**Comment by mooman219** [comment]
Soft breaks can't happen when there's no max width, but there can be hard breaks. I'll fix that for 0.4

**Comment by bschwind** [comment]
Makes sense, much appreciated!

**Comment by mooman219** [comment]
Should be fixed with the rewrite. Feel free to reopen this if it still shows up in 0.4 (not yet published, but on HEAD)
