### ISSUE TITLE
API design questions

### ISSUE THREAD

**Issue by bschwind** [mooman219/fontdue#43]
Hello again!

I'm running into a few issues which I'm not quite sure how to solve with fontdue's current API. I have an OpenGL glyph renderer and I pass it structs which are very similar to fontdue's `TextStyle`, but with a color attribute:

```rust
pub type Color = (f32, f32, f32, f32);

pub struct StyledText<'a> {
    pub text: &'a str,
    pub font: Font, // My own enum, you can ignore this
    pub color: (u8, u8, u8, u8),
}
```

After rasterizing, I have to correlate fontdue's output of `GlyphPosition`s back to my original output to determine which color to use for the glyph. I see you [added `include_whitespace`](https://github.com/mooman219/fontdue/issues/1#issuecomment-675933291) to support solving this problem, but I'm running into a whitespace issue that makes this a little difficult:

* When rasterizing, `'\n'` will map to the font's fallback character but `' '` will map to a zero-width and zero-height bitmap

I need to double check tomorrow, but from my tests the rasterizer seemed to handle it as a missing glyph, here was my debug output when rasterizing and packing into a glyph texture:

```
# The font is IBM Plex Sans, 300 weight
'あ': Ok(GlyphMissing)
'0': Ok(Packed)
'1': Ok(Packed)
':': Ok(Packed)
'4': Ok(Packed)
'8': Ok(Packed)
'\n': Ok(GlyphMissing)
'F': Ok(Packed)
'P': Ok(Packed)
'S': Ok(Packed)
':': Ok(Packed)
' ': Ok(WhitespaceChar)
'5': Ok(Packed)
'8': Ok(Packed)
```

I currently keep track of all this with a data structure of type `Vec<(Range<usize>, Color)>`, and I use `include_whitespace = true` so the character indices line up with the input. Let me know if you're interested in seeing the full code, it's kind of messy and it's a lot of extra work just to correlate the output back to the original input colors.

It all feels a bit fragile though and I'm wondering if you'd be open to possible API changes to make it easier to correlate.

For example, [`GlyphPosition`](https://docs.rs/fontdue/0.3.2/fontdue/layout/struct.GlyphPosition.html) could potentially hold an index which points to the `TextStyle` it came from.

Or if struct size is an issue, maybe `TextStyle` and `GlyphPosition` could be generic over a user-provided struct so it could default to a zero-sized struct but also allow us to optionally attach extra data that gets included in the output. [Here's](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fdd3d5ca5e24d12352d3f6eb5b9cfb6b) a brief example of that.

I could make an attempt at adding this to fontdue if it sounds like something you'd be interested in including in its API, but I just wanted to start a discussion here first. Thanks for the consideration!

**Comment by mooman219** [comment]
Thanks for the input! 

**Rasterization API**
Rasterization is fairly straight forward in that it will always produce a result as specified by the font. If the font doesn't include a glyph, the glyph in the 0 index is rasterized. What's happening in your case is the font does specify a bitmap for `' '`, it's just nothing, and it doesn't specify a bitmap for `'\n'`. Right now the only way to figure this out is to run `lookup_glyph_index` and check if it's 0. This probably should be info on the metrics.

**Layout API**
Okay being honest I threw together layout and it's definitely a sketchy prototype right now. I added a notice on the readme.md that layout is definitely immature in response to help set expectations currently. I agree that the user_data issue is a problem in the current API that needs to be solved, and it wasn't initially included because I've been the only user of `fontdue` for a long time and didn't need it.

I'm in the middle of a layout rewrite right now that fixes a couple of the bugs opened in the last 7 days. The rewrite so far leaves the API looking like:
```rust
pub fn main() {
    let font = include_bytes!("../resources/fonts/Roboto-Regular.ttf") as &[u8];
    let roboto_regular = fontdue::Font::from_bytes(font, fontdue::FontSettings::default()).unwrap();
    let mut layout = Layout::new(CoordinateSystem::PositiveYUp);
    layout.reset(&LayoutSettings {
        ..LayoutSettings::default()
    });
    let fonts = &[roboto_regular];
    layout.append(fonts, &TextStyle::new("Hello ", 35.0, 0));
    layout.append(fonts, &TextStyle::new("world!", 40.0, 0));
    for glyph in layout.glyphs() {
        println!("{:?}", glyph);
    }
}
```
This design lets me expose more intermediate data like line count / height / etc, and lets new text be more optimally laid out. Unfortunately, this API would make using a style index annoying for everyone involved, so it looks like stashing some metadata in there is the best option. I saw your PR and just learned that you can provide a default concrete type for a generic which is amazing. I'd be like to merge just the user data bit right now, but also I'll probably have the rewrite in a better state than current layout by this weekend and would rather wait for that.

**Comment by bschwind** [comment]
> What's happening in your case is the font does specify a bitmap for ' ', it's just nothing, and it doesn't specify a bitmap for '\n'. Right now the only way to figure this out is to run lookup_glyph_index and check if it's 0. This probably should be info on the metrics.

Makes sense! I think that's enough info for me to work around, combined with something like `char.is_whitespace()`

> Okay being honest I threw together layout and it's definitely a sketchy prototype right now

It's still quite nice and useful though, I appreciate that it exists!

> I'd be like to merge just the user data bit right now, but also I'll probably have the rewrite in a better state than current layout by this weekend and would rather wait for that.

Cool, I'll remove the `TextStyle` index code from the PR but you're also welcome to close it or use whatever code from it in your new layout system. I'm not sure yet if it will interact well with your new API but we can find out!

> The user data probably needs to be copy for this to work reasonably. Do these changes seem reasonable?

In my PR the user data actually ends up being borrowed and it all works out due to the lifetimes on the input `TextStyle` structs. So if that's the case the user data doesn't need to be `Copy` and ideally we can avoid doing any extra allocations for it by just having a reference to it. Once you have the new layout code I can take another crack at implementing it in that way.

Also as a disclaimer, I haven't made a text/rasterization API before so definitely compare my suggestions with existing work and ideally get other `fontdue` users' opinions. I'd feel terrible if an API suggestion that benefits me gets implemented and causes pain for everyone else 😅

**Comment by mooman219** [comment]
Mostly fixed with the last commit + your PR. There's a Copy + Clone restriction right now that'll deal with later. Feel free to open another issue with comments/concerns on the new API and

**Comment by bschwind** [comment]
> There's a Copy + Clone restriction right now that'll deal with later.

I see why you did that now, with separate calls to `layout()` being allowed now. It would definitely be nice to have a zero-copy version which uses references + lifetimes to metadata to avoid that. Let me know if you want to bounce ideas around on that, because although it's more efficient, the API is less ergonomic.

**Comment by mooman219** [comment]
Given the first rewrite is on HEAD now, if you have any suggestions or want to make another PR, I'm _very_ open to suggestions on making it more ergonomic. I really appreciate your first PR's design of not having the user deal with generics if they don't want to use the user data.

**Comment by bschwind** [comment]
I'll have to think about it some more, maybe some benchmarking is needed too. Another approach could be to use `Rc<UserData>`, but that could possibly end up being more expensive than just copying a small value around.

I see you have some benchmarks so I'll play around with those and see what I come up with :)

I added a version based on the current HEAD which uses lifetimes and references but like we discovered, it makes usage of the layout API less ergonomic, especially if you want to pass references to temporary variables in a call to `layout.append()`

**Comment by bschwind** [comment]
Hey again! I haven't done any benchmarks yet but I just integrated the latest version of `fontdue` into an open-source game I'm working on. It uses wgpu, you can check it out here:

https://github.com/bschwind/sus/compare/text?expand=1

The newer API is much nicer for knowing how to style the glyphs. The only snag I ran into was knowing to call `layout.reset(&layout_settings);` when rendering a block of text in a particular location, but that wasn't a big deal.

I need to structure my text drawing API similarly to fontdue so I can queue up a bunch of differently placed text blocks without incurring a GPU draw call for each one.

Anyway, great work on the library so far, seems to be working great!

**Comment by mooman219** [comment]
This is great! The latest commit is on crates.io under 0.4 right now, so no need to use a revision if you don't want to.

> The only snag I ran into was knowing to call `layout.reset(&layout_settings)`

My soft intention for `Layout` is that game logic owns it and passes it into the renderer/engine. This way you can actually leverage the perf from append (and eventually deleting) vs redoing layout for the whole text section

**Comment by bschwind** [comment]
> My soft intention for Layout is that game logic owns it and passes it into the renderer/engine. This way you can actually leverage the extra perf from append (and eventually deleting) vs redoing layout for the whole text section.

I see. Does that mean for every independent block of text (for example, a right-justified block of test and some centered text) I should maintain a separate `Layout` struct instead of calling `reset()` on the singular `Layout` struct I currently have?

**Comment by mooman219** [comment]
Up to you really to see how it works out in your use-case. Recalculating layout will be more expensive than reallocating heap.

Reusing `Layout` and just resetting state means you're not reallocating heap for state.
Reusing `Layout` and appending on the new characters means you're both not reallocating heap and not recalculating positioning.
