### ISSUE TITLE
Some fonts included on Macs rasterize totally blank.

### ISSUE THREAD

**Issue by kettle11** [mooman219/fontdue#52]
I was trying various fonts included in the Fonts directory on my Mac with the `raster-print.rs` example. I tried `HelveticaNeue.ttc` and `NewYork.ttf` and both produced metrics with a width and height > 0 but the output is totally blank.

(Also happy holidays!🎄🎄🎄)

**Comment by kettle11** [comment]
Adding some investigation: 

For `HelveticaNeue.ttc` the 'a' character appears, but the rest appear to be wrapping the opposite direction.

For `NewYork.ttf` `fontdue` is assuming the wrong wrapping direction and if the wrapping is reversed then the font appears for all characters I tested.

**Comment by kettle11** [comment]
I assume this is related to this issue somehow: https://github.com/RazrFalcon/ttf-parser/issues/43

**Comment by mooman219** [comment]
It's not that I'm assuming the wrong ordering, it's that the font is actually out of spec. Font engines like FreeType do a very expensive operation to check the winding order if it produces a blank output. I'm considering doing this on startup for `fontdue`

**Comment by kettle11** [comment]
Oh no. I assumed such mainstream fonts would be in spec. 

One thing I noticed is that I could take the absolute value of the produced float to get a reasonable looking result, but I assume that’s a bad idea for some reason?

**Comment by mooman219** [comment]
I have some fonts where that doesn't work :\, some transform operations specified in the font can also result in bad winding orders. Browser grade (chromium) handling of this is actually just guess and check.

**Comment by kettle11** [comment]
[Inter](https://github.com/rsms/inter) (a very popular font) also has this issue. 

'q' appears to be a reflection of 'p' so it rasterizes blank.

**Comment by simast** [comment]
Just hit the same issue with [Inconsolata](https://fonts.google.com/specimen/Inconsolata) font. In particular `)` glyph is rasterized with width/height but the bitmap is all empty bytes (0s).

**Comment by kettle11** [comment]
@simast I downloaded Inconsolata from your link and was not able to reproduce the issue with `Inconsolata-VariableFont_wdth,wght.ttf` or `Inconsolata-Regular.ttf`. 

Are you using another .ttf?

**Comment by kettle11** [comment]
Because I know how to have fun on New Years Eve I decided to try to put together a fix.

This commit in my fork fixes the issue for all fonts I tested: https://github.com/kettle11/fontdue/commit/3dce74117a5a78a3c2d88a7b2ee42bbfe71c68b4

The way it works is for each glyph it calculates and keeps track of the winding direction of the left most path (is path the correct term?).

If the left most path wraps counter-clockwise, then the glyph's points are reversed, otherwise they are not.

This is not a perfect solution. It will produce incorrect results if a path intended to be subtractive is left of a path intended to be solid. But it seems most fonts use subtractive (counter-clockwise) paths to represent holes on the interior of as solid area.

Likely it introduces a small performance hit, but I have not tested that yet.

I also have not rigorously tested this with a wide array of fonts, but it seems promising for the few I did test.

**Comment by simast** [comment]
> I downloaded Inconsolata from your link and was not able to reproduce the issue with Inconsolata-VariableFont_wdth,wght.ttf or Inconsolata-Regular.ttf.

That's weird as the font file I am seeing this issue is `static\Inconsolata-Regular.ttf` in the download.

> This commit in my fork fixes the issue for all fonts I tested

Just tested your changes and I can confirm that this also fixes Inconsolata font issue with `)` glyph I described above.

**Comment by rkanati** [comment]
Seeing the same symptoms with `iosevka-regular.ttf` - correct metrics, but the image is a big ol' bucket of `0`. I'll have a go with kettle's fix and see what happens.

**Comment by mooman219** [comment]
I'll use a heuristic to guess the winding order of the glyph on startup.  Should be in the spirit of what Kettle11 did

**Comment by mooman219** [comment]
This probably works https://github.com/mooman219/fontdue/commit/cb2e9b2373d094b9b84d52beefefff3e73dc6254. Can anyone confirm they still have the issue with this fix?

**Comment by mooman219** [comment]
I decided to make a more robust test, so I am now testing all glyphs in the following fonts:

```
Roboto-Regular.ttf
RobotoMono-Regular.ttf
Comfortaa-Regular.ttf
Inconsolata-Regular.ttf
FasterOne-Regular.ttf
Exo2-Regular.otf
GreatVibes-Regular.otf
modernpics.otf
```

I found an issue in my original heuristic so I decided to just do it right the second time and added some heavier math to actually calculate the winding right.
