### ISSUE TITLE
Does this library supports rendering outlined gylphs?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [mooman219/fontdue#58]
I'm currently looking for several font libraries available in Rust.  One feature I want is to render outlined glyph, as in [Glyph Stroker](https://www.freetype.org/freetype2/docs/reference/ft2-glyph_stroker.html) in FreeType (expected output: [like this](https://stackoverflow.com/questions/20874056/draw-text-outline-with-freetype)).  I looked up the docs for this library but could not find plausible one.  Does this library currently support the feature?   (Additionally, do you know some other library for Rust that supports this?  You don't have to answer this question in the parenthesis)

**Comment by mooman219** [comment]
No this doesn't handle outline, the algorithm only works to completely fill in glyphs. No plans to support that unless something clean is PR'd 

I'm not aware of anything light weight that can do this in rust off the top of my head. I'm sure you can do this in Piet or Pathfinder, but those might be a bit involved.
