### ISSUE TITLE
Enumerate all characters in font

### ISSUE THREAD

**Issue by zovt** [mooman219/fontdue#59]
Hello, I'm looking into using fontdue for font atlas rendering, but as far as I can tell, there is no way to enumerate the characters in `Font`. I'm wondering what your thoughts on supporting something like that are? I'm happy to do the initial work for that, seems straightforward enough

**Comment by aclysma** [comment]
As it happens just this afternoon I wrote a snippet of code that does exactly this. FYI calling `subtable.glyph_index` on every character in a font (especially a CJK font with 1000s of characters) is expensive so I filter the range of unicode characters I want to rasterize. 

This is almost copy-paste from fontdue's loading code, so +1 for adding an API to access the data fontdue is collecting! (Would also be nice to be able to filter to a list of ranges. By far, fontdue iterating every character in a large CJK font is the slowest part of my code.)


```rust
    let character_ranges_to_include = vec![
        (32, 128),
        //(0x4e00, 0x5FCC) // large range of CJK characters for testing
    ];

    let mut characters_to_include = vec![];

    use ttf_parser::{Face, GlyphId, TableName};
    let face = Face::from_slice(font_data, 0).unwrap();

    for subtable in face.character_mapping_subtables() {
        subtable.codepoints(|codepoint| {
            for range in &character_ranges_to_include {
                if codepoint >= range.0 && codepoint <= range.1 {
                    if let Some(glyph_id) = subtable.glyph_index(codepoint) {
                        //let name = face.glyph_name(glyph_id);
                        //println!("glyph codepoint: {} {:?} id: {:?} name: {:?}", codepoint, std::char::from_u32(codepoint), glyph_id, name);

                        characters_to_include.push(std::char::from_u32(codepoint).unwrap());
                    }
                }
            }
        });
    }
```

```
read metadata 0.40333298ms
load font to fontdue 232.11732ms <-- could be reduced by filtering ranges of characters
rasterize 0.7775ms
create rects to place 0.060416ms
generated placement for 512x512 texture in 0.148333ms
determined placement 0.431833ms
blit to single texture 0.173125ms
```

**Comment by mooman219** [comment]
You can achieve enumerating over all the glyph data like: https://github.com/mooman219/fontdue/blob/master/tests/letter_render_tests.rs#L70
