### ISSUE TITLE
Documentation for horizontal_line_metrics is confusing

### ISSUE THREAD

**Issue by avl** [mooman219/fontdue#63]
I just noticed that the documentation for Font::horizontal_line_metrics states:

"The new line height for the font. Only populated for fonts with vertical text layout metrics."

Is the text correct? Does horizontal_line_metrics only work for fonts with 'vertical text layout metrics'? Shouldn't it be 'horizontal text layout metrics'?

**Comment by mooman219** [comment]
Okay so bear with me, these are really just the terms used in the spec and it's confusing and bad and I succumbed to that when writing those sentence. I made an attempt to make it more clear in  1bb8a89
