### ISSUE TITLE
Error: f32::abs function not found

### ISSUE THREAD

**Issue by GerodruS** [mooman219/fontdue#72]
Hi!
I found something strange after updating dependencies for my project recently.
Rust compiler can't build fontdue library with a message:
```
  --> /Users/gerodrus/.cargo/registry/src/github.com-1ecc6299db9ec823/fontdue-0.5.1/src/platform/float/get_bitmap.rs:18:62
   |
18 |             *(output.get_unchecked_mut(i)) = f32::clamp(f32::abs(height) * 255.9, 0.0, 255.0) as u8;
   |                                                              ^^^ function or associated item not found in `f32`
```
rustc version is 1.52.1 with target -- stable-aarch64-apple-darwin (Apple Silicon)
My project is using macroquad library, that depends on fontdue.
If I can provide any further information, feel free to ask.

**Comment by optozorax** [comment]
Same for the target `wasm32-unknown-unknown`

**Comment by mooman219** [comment]
We all make mistakes, one second
