### ISSUE TITLE
Scale units

### ISSUE THREAD

**Issue by dhardy** [mooman219/fontdue#76]
The `px` scale units appear to be pixels per Em. This could be clearer in the docs.

If you want inspiration for the docs, see: https://github.com/kas-gui/kas-text/blob/master/src/fonts/mod.rs#L38

Ironically my library exposes scale via "DPU" (pixels for font unit) which is what fontdue uses internally, thus I have to multiply by units-per-em so that fontdue can divide again (in `Font::scale_factor`, called by various functions). Not really an issue.

**Comment by mooman219** [comment]
Do you have a recommendation for how `scale = px / self.units_per_em` is defined in the documentation? The current docs "Calculates the glyph's outline scale factor for a given px size" and algorithm 

___

Unrelated rant, DPI is a horrible parameter to ever expect the user to reasonably provide because most users have absolutely no idea how to surface the current monitor's DPI from the OS/Hardware and will just slam in 72/96 as the DPI because they don't know it even though some devices have 400+ DPI, so now we have OS scale factors because everyone misused DPI related APIs.

**Comment by dhardy** [comment]
Just saying that scale has units of "pixels per Em" would be an improvement IMO.

Perhaps DPI is a horrible parameter to show users... I've been using KDE's "force font DPI" setting on a high-DPI laptop for years but apparently many people didn't realise that was an option. Today however most systems have some kind of scaling factor input (except I think phones just show various sizes with examples but no numbers), so it's less of an issue. For many Rustaceans, the winit library provides a scaling factor (which can be converted to a DPI).

**Comment by mooman219** [comment]
> Just saying that scale has units of "pixels per Em" would be an improvement IMO.

Sounds good, I'll make the change tomorrow!

___

> For many Rustaceans, the winit library provides a scaling factor (which can be converted to a DPI).

Winit does indeed expose the scaling factor, but not DPI. The scaling factor is not relative to a DPI and is an arbitrary value set by the OS which can be configured by the user sometimes. The actual DPI is not used as part of the calculation, so calling anything DPI, or consuming DPI as a parameter is entirely worthless. For example, on Windows it's just a control panel setting, on Android it's usually relative to the DPI within some ranges (i.e. 640dpi+ gets 4.0, 480-640 gets 3.0, etc), on iOS it's more often based on the screen size and not strictly any DPI specifically.

**Comment by dhardy** [comment]
> Winit does indeed expose the scaling factor, but not DPI.

We want a font size in px/em or some such, and no, we don't really care about px/inch. We actually care about how big the user wants, say, a 10pt font to appear on their screen. 10pt means 10 * (1/72 inch) / Em, or 10/72 inches/Em, for most of us.

I think it's fair to assume that the reported scaling factor is relative to a *standard* DPI of 96, on desktop/laptop computers, most of the time? Thus we get 10/72 * 96 pixels/Em, approx 13 px/Em. Except on MacOS, where apparently "point" is redefined as DPI, so a 10pt font is 10px/Em if displayed on a 96DPI screen. Whatever, you just need to ask the user whether their font size is in "MacOS Points" or "Standard Points".

But, you say, we have a scaling factor, not a DPI. Scaling factors are designed to be used relative to the platform standard. So with a factor of 2 you just double the px/Em number.

Then you have iOS, Android etc. I've yet to dig into what units they use.

Did I mention that at no point above do we actually care what the *real* DPI of the screen is? If the user has a 1080p 13" screen (169 DPI) but chooses a scale factor of 1.5, then our 10pt font becomes 10*96/72*1.5 = 20 px/Em.

**Comment by mooman219** [comment]
> Did I mention that at no point above do we actually care what the real DPI of the screen is? If the user has a 1080p 13" screen (169 DPI) but chooses a scale factor of 1.5, then our 10pt font becomes 10*96/72*1.5 = 20 px/Em.

My issue with this is why are we using "DPI" at all in any documentation? What's the point of 10\***96/72**\*1.5? Why pretend the logical DPI of a 90s CRT is a relevant parameter when we have perfectly fine DPI agnostic scales like pixels per em unit?

**Comment by dhardy** [comment]
Well, because people are used to writing font sizes in points, which, like it or not, are derived from inches. If you're only interested in games then sure you can ignore this but if you want to write desktop software, people will probably want comparable units to what they already use.

**Comment by mooman219** [comment]
Point scaling in chrome and windows isn't derived from inches or the actual display DPI, it's based on the browser/os scale factor. Desktop, game, and web apps don't leverage DPI in any capacity aside from any ceremony involved in configuring/providing parameters for a library that doesn't actually care.

**Comment by dhardy** [comment]
A scaling factor is a relative measure: it is relative to some standard, usually 96 DPI.

You're *kind of* right that it would be simpler describe fonts via px/Em — except that scaling factors are now common-place (because they're a useful way to scale all UI elements simultaneously), and if you have, say, 12px fonts at 1.5 scale factor, that's just another source of confusion (is that really 12px or 18px?).

**Comment by mooman219** [comment]
But we're in the situation right now with more parameters, like taking FreeType, you have the glyph pixel size (width/height), screen dpi (horizontal/vertical), and then the OS scale factor on top of it, I think we can move on from DPI. Point and pixels in the browser also don't relate to the number of points or pixels the glyph actually is either.
