### ISSUE TITLE
Font::from_bytes creates NonZeroU16s containing zero

### ISSUE THREAD

**Issue by caelunshun** [mooman219/fontdue#86]
https://github.com/mooman219/fontdue/blob/9483ae1ec3674ab1a786b0ad12e6b987c2023714/src/font.rs#L242-L244

According to [the `std` docs](https://doc.rust-lang.org/beta/std/num/struct.NonZeroU16.html#method.new_unchecked), a `NonZeroU16` containing 0 is always undefined behavior. It's unclear what the comment is trying to say with "the result is desirable," but undefined behavior should never be a desired result.

I think the solution here is to switch to normal `u16`s, though I'm not sure what the motivation was for using `NonZeroU16` to start with.

**Comment by mooman219** [comment]
https://github.com/mooman219/fontdue/blob/9483ae1ec3674ab1a786b0ad12e6b987c2023714/src/font.rs#L563-L567

It's a layout optimization, that makes the above lookup work with fewer branches. `Option<NonZeroU16>`  is defined to reuse 0 as the None identifier. Specifically this invariant is defined:
```rust
assert_eq!(size_of::<Option<core::num::NonZeroU16>>(), size_of::<u16>());
```
The cases I'm accounting for:
- the mapping is undefined and therefore missing.
- the mapping is defined to be missing.
- the mapping is defined.

In this setup all of these cases return a valid u16 that can be used as the lookup.
