### ISSUE TITLE
Kerning is not parsed

### ISSUE THREAD

**Issue by fxdave** [mooman219/fontdue#87]
I tried the master branch with the Public Sans google font.
It looks like it cannot parse the font well because the `font.horizontal_kern` will be None.

```rust
use fontdue::layout::{CoordinateSystem, Layout, LayoutSettings, TextStyle};

fn main() {
    let font = include_bytes!(".......ttf") as &[u8];
    let font = fontdue::Font::from_bytes(font, fontdue::FontSettings::default()).unwrap();

    let w = "AV" // this char pair has kerning
        .chars()
        .scan(None, |prev: &mut Option<char>, c| {
            let kern = prev
                .and_then(|prev_c| font.horizontal_kern(prev_c, c, 100.))
                .unwrap_or(0.); // this is always 0 because font.horizontal_kern is None
            *prev = Some(c);
            Some(font.metrics(c, 100.).advance_width + kern)
        })
        .sum::<f32>();
    println!(" {:#?} ", w);
}
```

**Comment by mooman219** [comment]
This is actually the correct behavior. [Public Sans Regular](https://fonts.google.com/specimen/Public+Sans) has no kerning table.

![image](https://user-images.githubusercontent.com/865769/135379210-c38b453c-85fa-4c63-9790-4aa5178f593f.png)

**Comment by fxdave** [comment]
![image](https://user-images.githubusercontent.com/12275699/135449975-545e2f01-32d2-4aa1-a1c1-80ec8238ab02.png)
Why is AV closer to each other if this is the case?

**Comment by mooman219** [comment]
The font may be using one of the shaping tables for kerning information like GPOS, which the rust text libraries don't generally support yet (i.e. Rusttype glyphbrush ab_glyph). We're all just parsing the `kern` table and if it's not there we can't kern.

**Comment by fxdave** [comment]
I see. Thanks
