### ISSUE TITLE
Doesn't compile with "+soft-float": Compiler LLVM Error: "Do not know how to split the result of this operator"

### ISSUE THREAD

**Issue by phip1611** [mooman219/fontdue#98]
This is probably a bug in the Rust compiler but maybe this can be easily fixed by a workaround or someone already has experience with this error?

When this crate gets compiled with `cargo rustc -- -C target-feature=+soft-float` cargo exits with an error and LLVM says: "Do not know how to split the result of this operator"

I already checked the dependencies `ttf-parser` and `hashbrown`, but the problem occurs only in `fontdue` with different Rust compiler versions accross stable and nightly releases. Anyone has an idea?

**Comment by phip1611** [comment]
Related issue from 2019: https://github.com/rust-lang/rust/issues/61721

**Comment by phip1611** [comment]
Disabling the `simd`-feature doesn't change anything, unfortunately.

**Comment by mooman219** [comment]
Do you have a stack trace or anything that narrows down the investigation?

**Comment by phip1611** [comment]
In the meantime, I found out that the problem occurs in `hashbrown`-dependency.

Not when building the library but when building an executable, that uses it. Minimal example:

```rust
fn main() {
    let _book_reviews = hashbrown::HashMap::<(), ()>::new();
}
```

Compiled with `$ cargo  rustc --bin bug -- -C target-feature=+soft-float,-sse,-sse2,-x87`

**Comment by mooman219** [comment]
I'm going to tentatively mark this as wontfix since it's not clear to me that the actual issue is in `fontdue`, but leave this bug open for now because this isn't the first time fontdue exposed a bug in llvm.

**Comment by Hugo4IT** [comment]
Is there a workaround for this? Or will I just have to sit and wait for LLVM to fix this...

**Comment by phip1611** [comment]
@Hugo4IT the workaround is to either use the crate without the simd-feature and soft-float or to pre-render all characters, such as https://crates.io/crates/noto-sans-mono-bitmap does it

**Comment by Hugo4IT** [comment]
Using the crate without the SIMD feature still brought up some linker errors, but those were solvable by simply copying the `fminf` and `fmaxf` functions from the `libm` source code, and adding them to my code with `#[no_mangle]`, I guess Rust couldn't find them.

**Comment by mooman219** [comment]
> Using the crate without the SIMD feature still brought up some linker errors, but those were solvable by simply copying the `fminf` and `fmaxf` functions from the `libm` source code, and adding them to my code with `#[no_mangle]`, I guess Rust couldn't find them.

@Hugo4IT seems strange, I don't use min/max in fontdue. Disabling simd should be sufficient. What does your environment look like?

**Comment by phip1611** [comment]
@Hugo4IT  @mooman219  this is a bug by Rust when using the "+soft-float" feature on x86. 

more info: https://github.com/rust-lang/rust/issues/62729
